# Created by: Hans Petter Selasky <hselasky@FreeBSD.org>
# $FreeBSD$

PORTNAME=	qfasttrackultractl
PORTVERSION=	1.0.0
CATEGORIES=	audio
MASTER_SITES=	http://www.selasky.org/hans_petter/distfiles/ \
		http://home.selasky.org:8192/distfiles/

MAINTAINER=	hselasky@FreeBSD.org
COMMENT=	FastTrackUltra control panel application

LICENSE=	BSD2CLAUSE

USES=		qmake tar:bzip2
USE_QT4=	gui moc_build rcc_build

.include <bsd.port.mk>
