# Created by: Hans Petter Selasky <hselasky@FreeBSD.org>
# $FreeBSD$

PORTNAME=	virtual_oss_ctl
PORTVERSION=	1.0.5
CATEGORIES=	audio
MASTER_SITES=	http://www.selasky.org/hans_petter/distfiles/ \
		http://home.selasky.org:8192/distfiles/

MAINTAINER=	hselasky@FreeBSD.org
COMMENT=	A grapical control panel for the virtual OSS daemon

LICENSE=	BSD
USES=		qmake tar:bzip2

USE_QT4=	gui qmake_build moc_build rcc_build

.include <bsd.port.mk>

