# Created by: hselasky <hselasky@freebsd.org>
# $FreeBSD$

PORTNAME=	atinout
DISTVERSION=	0.9.2
PORTREVISION=
CATEGORIES=	comms
MASTER_SITES=	SF

MAINTAINER=	hselasky@FreeBSD.org
COMMENT=	Receive and Send AT commands from the command line

LICENSE=	GPLv3

MAN1=		atinout.1

USES=		cmake

.include <bsd.port.mk>
